window._env_ = {
  IO_PAY_PORTAL_API_HOST: "http://localhost:1234",
  IO_PAY_PORTAL_ENV: "develop",
  IO_PAY_PORTAL_PAY_WL_HOST: "http://localhost:1234",
  IO_PAY_PORTAL_API_REQUEST_TIMEOUT: "5000",
  IO_PAY_PORTAL_PAY_WL_POLLING_ATTEMPTS: "10",
  IO_PAY_PORTAL_PAY_WL_POLLING_INTERVAL: "3000",
}
